import os


def generate_html_report(domain: str, report_data: dict):
    os.makedirs("reports", exist_ok=True)

    filename = f"reports/{domain}_report.html"

    findings = report_data.get("findings", [])
    subdomains = report_data.get("subdomains", [])
    open_ports = report_data.get("open_ports", [])
    tech = report_data.get("technology_fingerprint", {})

    html = f"""
<html>
<head>
    <title>Attack Surface Report - {domain}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 40px;
            background-color: #f8f9fa;
            color: #2c3e50;
        }}

        .container {{
            background: white;
            padding: 30px;
            border-radius: 8px;
        }}

        h1 {{
            color: #2c3e50;
        }}

        h2 {{
            color: #34495e;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }}

        .finding {{
            border: 1px solid #ddd;
            padding: 12px;
            margin: 12px 0;
            background: #ffffff;
        }}

        .medium {{
            border-left: 6px solid orange;
        }}

        .low {{
            border-left: 6px solid green;
        }}

        .informational {{
            border-left: 6px solid blue;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }}

        th, td {{
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }}

        th {{
            background-color: #ecf0f1;
        }}
    </style>
</head>

<body>
<div class="container">

    <h1>Attack Surface Discovery Report</h1>

    <h2>Target</h2>
    <p>{domain}</p>

    <h2>Executive Summary</h2>
    <p>
        This report was automatically generated by the Attack Surface Discovery Toolkit.
        The assessment identified publicly accessible assets, DNS records, SSL certificate
        information, subdomains, open ports and security header findings.
    </p>

    <h2>Asset Inventory</h2>
    <table>
        <tr>
            <th>Subdomain</th>
            <th>IP Address</th>
        </tr>
"""

    for subdomain in subdomains:
        html += f"""
        <tr>
            <td>{subdomain['subdomain']}</td>
            <td>{subdomain['ip']}</td>
        </tr>
"""

    html += """
    </table>

    <h2>Open Ports</h2>
"""

    if open_ports:
        html += "<ul>"
        for port in open_ports:
            html += f"<li>Port {port} is open</li>"
        html += "</ul>"
    else:
        html += "<p>No open ports discovered.</p>"

    html += f"""
    <h2>Technology Fingerprinting</h2>
    <table>
        <tr><th>Field</th><th>Value</th></tr>
        <tr><td>URL</td><td>{tech.get('url')}</td></tr>
        <tr><td>Status Code</td><td>{tech.get('status_code')}</td></tr>
        <tr><td>Server</td><td>{tech.get('server')}</td></tr>
        <tr><td>Content Type</td><td>{tech.get('content_type')}</td></tr>
        <tr><td>Strict Transport Security</td><td>{tech.get('strict_transport_security')}</td></tr>
        <tr><td>Content Security Policy</td><td>{tech.get('content_security_policy')}</td></tr>
        <tr><td>X-Frame-Options</td><td>{tech.get('x_frame_options')}</td></tr>
        <tr><td>X-Content-Type-Options</td><td>{tech.get('x_content_type_options')}</td></tr>
    </table>

    <h2>Findings</h2>
"""

    if findings:
        for finding in findings:
            severity = finding["severity"].lower()

            html += f"""
            <div class="finding {severity}">
                <b>Severity:</b> {finding['severity']}<br>
                <b>Finding:</b> {finding['finding']}<br>
                <b>Recommendation:</b> {finding['recommendation']}
            </div>
"""
    else:
        html += "<p>No findings detected.</p>"

    html += """
</div>
</body>
</html>
"""

    with open(filename, "w", encoding="utf-8") as report_file:
        report_file.write(html)

    return filename
